// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	github.proto

It has these top-level messages:
	GithubSearchRequest
	GithubSearchResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type GithubSearchRequest struct {
	S string `protobuf:"bytes,1,opt,name=s" json:"s,omitempty"`
}

func (m *GithubSearchRequest) Reset()                    { *m = GithubSearchRequest{} }
func (m *GithubSearchRequest) String() string            { return proto1.CompactTextString(m) }
func (*GithubSearchRequest) ProtoMessage()               {}
func (*GithubSearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GithubSearchRequest) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

type GithubSearchResponse struct {
	V   string `protobuf:"bytes,1,opt,name=v" json:"v,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *GithubSearchResponse) Reset()                    { *m = GithubSearchResponse{} }
func (m *GithubSearchResponse) String() string            { return proto1.CompactTextString(m) }
func (*GithubSearchResponse) ProtoMessage()               {}
func (*GithubSearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GithubSearchResponse) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func (m *GithubSearchResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto1.RegisterType((*GithubSearchRequest)(nil), "proto.GithubSearchRequest")
	proto1.RegisterType((*GithubSearchResponse)(nil), "proto.GithubSearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Github service

type GithubClient interface {
	GetRepositories(ctx context.Context, in *GithubSearchRequest, opts ...grpc.CallOption) (*GithubSearchResponse, error)
}

type githubClient struct {
	cc *grpc.ClientConn
}

func NewGithubClient(cc *grpc.ClientConn) GithubClient {
	return &githubClient{cc}
}

func (c *githubClient) GetRepositories(ctx context.Context, in *GithubSearchRequest, opts ...grpc.CallOption) (*GithubSearchResponse, error) {
	out := new(GithubSearchResponse)
	err := grpc.Invoke(ctx, "/proto.Github/GetRepositories", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Github service

type GithubServer interface {
	GetRepositories(context.Context, *GithubSearchRequest) (*GithubSearchResponse, error)
}

func RegisterGithubServer(s *grpc.Server, srv GithubServer) {
	s.RegisterService(&_Github_serviceDesc, srv)
}

func _Github_GetRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GithubSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubServer).GetRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Github/GetRepositories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubServer).GetRepositories(ctx, req.(*GithubSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Github_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Github",
	HandlerType: (*GithubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRepositories",
			Handler:    _Github_GetRepositories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.proto",
}

func init() { proto1.RegisterFile("github.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xca, 0x5c, 0xc2,
	0xee, 0x60, 0xe1, 0xe0, 0xd4, 0xc4, 0xa2, 0xe4, 0x8c, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12,
	0x21, 0x1e, 0x2e, 0xc6, 0x62, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xc6, 0x62, 0x25, 0x33,
	0x2e, 0x11, 0x54, 0x45, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x20, 0x55, 0x65, 0x30, 0x55, 0x65,
	0x42, 0x02, 0x5c, 0xcc, 0xa9, 0x45, 0x45, 0x12, 0x4c, 0x60, 0x3e, 0x88, 0x69, 0x14, 0xc6, 0xc5,
	0x06, 0xd1, 0x27, 0xe4, 0xc3, 0xc5, 0xef, 0x9e, 0x5a, 0x12, 0x94, 0x5a, 0x90, 0x5f, 0x9c, 0x59,
	0x92, 0x5f, 0x94, 0x99, 0x5a, 0x2c, 0x24, 0x05, 0x71, 0x88, 0x1e, 0x16, 0xeb, 0xa5, 0xa4, 0xb1,
	0xca, 0x41, 0x6c, 0x55, 0x62, 0x48, 0x62, 0x03, 0xcb, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x89, 0xbb, 0x7a, 0xa0, 0xd2, 0x00, 0x00, 0x00,
}
